"""auto

Revision ID: f5f2727af4b3
Revises: 199c326a8f34
Create Date: 2026-01-04 18:53:42.905560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5f2727af4b3"
down_revision: Union[str, Sequence[str], None] = "199c326a8f34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE INDEX articles_embeddings_ivfflat_idx
        ON articles
        USING ivfflat (embeddings vector_cosine_ops)
        WITH (lists = 100);
    """)

    op.execute("ANALYZE articles;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS articles_embeddings_ivfflat_idx;")
    # ### end Alembic commands ###
